/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GeneticsRouteImport } from './routes/genetics'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as VolcanoRouteImport } from './routes/volcano'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneticsRoute = GeneticsRouteImport.update({
  id: '/genetics',
  path: '/genetics',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const VolcanoRoute = VolcanoRouteImport.update({
  id: '/volcano',
  path: '/volcano',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genetics': typeof GeneticsRoute
  '/launchpad': typeof LaunchpadRoute
  '/sandbox': typeof SandboxRoute
  '/volcano': typeof VolcanoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genetics': typeof GeneticsRoute
  '/launchpad': typeof LaunchpadRoute
  '/sandbox': typeof SandboxRoute
  '/volcano': typeof VolcanoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/genetics': typeof GeneticsRoute
  '/launchpad': typeof LaunchpadRoute
  '/sandbox': typeof SandboxRoute
  '/volcano': typeof VolcanoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/genetics' | '/launchpad' | '/sandbox' | '/volcano'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/genetics' | '/launchpad' | '/sandbox' | '/volcano'
  id: '__root__' | '/' | '/genetics' | '/launchpad' | '/sandbox' | '/volcano'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneticsRoute: typeof GeneticsRoute
  LaunchpadRoute: typeof LaunchpadRoute
  SandboxRoute: typeof SandboxRoute
  VolcanoRoute: typeof VolcanoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genetics': {
      id: '/genetics'
      path: '/genetics'
      fullPath: '/genetics'
      preLoaderRoute: typeof GeneticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volcano': {
      id: '/volcano'
      path: '/volcano'
      fullPath: '/volcano'
      preLoaderRoute: typeof VolcanoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneticsRoute: GeneticsRoute,
  LaunchpadRoute: LaunchpadRoute,
  SandboxRoute: SandboxRoute,
  VolcanoRoute: VolcanoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
